framework:
    cache:
        app: app.cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        pools:
            app_cache:
                adapter: app.cache.adapter.redis
            doctrine.result_cache_pool:
                adapter: app.cache.adapter.redis
            doctrine.system_cache_pool:
                adapter: app.cache.adapter.redis
services:
    app.cache.adapter.redis:
        parent: 'cache.adapter.redis'
        arguments:
            $defaultLifetime: 86400 # 24h
        tags:
            - { name: 'cache.pool', namespace: 'app_cache' }