framework:
    cache:
        pools:
            app_cache:
                default_lifetime: 10800 #3 Hr in Prod
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            doctrine.result_cache_pool:
                default_lifetime: 10800
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            doctrine.system_cache_pool:
                default_lifetime: 10800
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'